INSERT INTO public.cargo (name, weight) VALUES ('Мешок цемента', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон кирпича', 1200);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка нефти', 200);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон стали', 1000);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с водой', 800);
INSERT INTO public.cargo (name, weight) VALUES ('Коробка с яблоками', 10);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок картофеля', 25);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с мебелью', 1500);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с молоком', 900);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка бензина', 150);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон бумаги', 500);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с книгами', 20);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с кирпичом', 1400);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон ткани', 200);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с игрушками', 600);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с овощами', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок муки', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с кирпичом', 1300);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон пластика', 300);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с вином', 250);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с фруктами', 15);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок с сахаром', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с плиткой', 1100);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон ковра', 350);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с одеждой', 500);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с инструментами', 25);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок цемента', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с маслом', 850);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с химикатами', 180);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон линолеума', 400);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с рыбой', 20);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок цемента', 60);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с камнем', 1500);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон алюминия', 700);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с электроникой', 1000);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с напитками', 25);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок картофеля', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с соком', 950);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с водой', 200);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон стали', 900);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с овощами', 35);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок муки', 60);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с кирпичом', 1200);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон бумаги', 600);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с игрушками', 700);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с книгами', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок с зерном', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с молоком', 750);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с медом', 180);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон ткани', 250);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с фруктами', 20);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок цемента', 55);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с плиткой', 1300);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон пластика', 350);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с мебелью', 1600);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с овощами', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок цемента', 45);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с водой', 900);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с вином', 220);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон ковра', 400);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с инструментами', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок картофеля', 35);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с кирпичом', 1400);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон линолеума', 450);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с одеждой', 600);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с рыбой', 25);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок муки', 55);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с маслом', 800);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с химикатами', 190);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон стали', 1100);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с напитками', 35);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок цемента', 65);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с камнем', 1600);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон алюминия', 800);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с электроникой', 1100);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с овощами', 45);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок картофеля', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с соком', 1000);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с водой', 250);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон бумаги', 700);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с фруктами', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок муки', 65);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с кирпичом', 1500);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон ткани', 300);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с игрушками', 800);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с книгами', 35);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок с зерном', 55);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с молоком', 850);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с медом', 200);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон пластика', 400);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с овощами', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок цемента', 70);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с плиткой', 1400);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон ковра', 450);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с мебелью', 1700);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с фруктами', 35);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок цемента', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с водой', 950);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с вином', 240);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон линолеума', 500);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с инструментами', 35);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок картофеля', 45);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с кирпичом', 1600);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон стали', 1200);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с одеждой', 700);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с рыбой', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок муки', 70);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с маслом', 850);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с химикатами', 210);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон алюминия', 900);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с напитками', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок цемента', 75);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с камнем', 1700);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон бумаги', 800);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с электроникой', 1200);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с овощами', 55);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок картофеля', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с соком', 1050);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с водой', 300);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон ткани', 350);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с фруктами', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок муки', 75);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с кирпичом', 1700);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон пластика', 450);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с игрушками', 900);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с книгами', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок с зерном', 60);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с молоком', 900);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с медом', 220);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон ковра', 500);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с овощами', 60);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок цемента', 80);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с плиткой', 1500);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон линолеума', 550);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с мебелью', 1800);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с фруктами', 45);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок цемента', 55);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с водой', 1000);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с вином', 260);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон стали', 1300);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с инструментами', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок картофеля', 55);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с кирпичом', 1800);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон бумаги', 900);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с одеждой', 800);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с рыбой', 35);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок муки', 80);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с маслом', 900);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с химикатами', 220);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон алюминия', 1000);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с напитками', 45);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок цемента', 85);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с камнем', 1800);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон ткани', 400);
INSERT INTO public.cargo (name, weight) VALUES ('Контейнер с электроникой', 1300);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с овощами', 65);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок картофеля', 60);
INSERT INTO public.cargo (name, weight) VALUES ('Паллет с соком', 1100);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка с водой', 350);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон пластика', 500);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик с фруктами', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок муки', 85);
INSERT INTO public.cargo (name, weight) VALUES ('Поддон с кирпичом', 1900);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон ковра', 550);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок картошки', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик яблок', 20);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка меда', 200);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон обоев', 15);
INSERT INTO public.cargo (name, weight) VALUES ('Палет с кирпичами', 1000);
INSERT INTO public.cargo (name, weight) VALUES ('Бидон масла', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Большая коробка инструментов', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок цемента', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик стеклянной посуды', 25);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка воды', 150);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон коврового покрытия', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Коробка пластиковых труб', 60);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок угля', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик книг', 25);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка кислоты', 300);
INSERT INTO public.cargo (name, weight) VALUES ('Балка дерева', 200);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон проволоки', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок корма для животных', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик стеклобанок', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка краски', 150);
INSERT INTO public.cargo (name, weight) VALUES ('Коробка деталей машин', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок сахара', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик овощей', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка спирта', 250);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон проволочного сетчатого материала', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Палет с керамической плиткой', 800);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок песка', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик мяса', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка масла для трансформаторов', 500);
INSERT INTO public.cargo (name, weight) VALUES ('Банка краски', 20);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик мороженого', 15);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка вина', 200);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон ткани', 20);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок риса', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик молока', 20);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка аммиака', 300);
INSERT INTO public.cargo (name, weight) VALUES ('Коробка канцелярских товаров', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок зерна', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик мебели', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка керосина', 200);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон линолеума', 35);
INSERT INTO public.cargo (name, weight) VALUES ('Коробка игрушек', 25);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок соли', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик хлеба', 20);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка химических реагентов', 250);
INSERT INTO public.cargo (name, weight) VALUES ('Балка железа', 300);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон кабеля', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок корма для птиц', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик посуды', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка керамзита', 150);
INSERT INTO public.cargo (name, weight) VALUES ('Коробка одежды', 25);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок картона', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик пива', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка нефти', 250);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон обивочной ткани', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Палет с кирпичами (кирпичи стандартного размера)', 1200);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок удобрений', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик морепродуктов', 35);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка кислоты серной', 400);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон турфа', 25);
INSERT INTO public.cargo (name, weight) VALUES ('Коробка инструментов для сада', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок минеральных удобрений', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик канцелярских товаров', 25);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка уксуса', 150);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон ковров', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Балка алюминия', 250);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок гипса', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик овощного сока', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка питьевой воды', 200);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон строительной сетки', 40);
INSERT INTO public.cargo (name, weight) VALUES ('Коробка медицинских препаратов', 25);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок льда', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик мела', 20);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка ацетилена', 200);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон облицовочного камня', 60);
INSERT INTO public.cargo (name, weight) VALUES ('Палет с гипсокартоном', 900);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок цветов', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик красителя для бетона', 25);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка антифриза', 150);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон паркета', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Коробка игровых консолей', 20);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок семян', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик мороженого пломбира', 15);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка бензина', 200);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон ковролина', 35);
INSERT INTO public.cargo (name, weight) VALUES ('Балка стали', 300);
INSERT INTO public.cargo (name, weight) VALUES ('Мешок угольных брикетов', 50);
INSERT INTO public.cargo (name, weight) VALUES ('Ящик свежих ягод', 30);
INSERT INTO public.cargo (name, weight) VALUES ('Бочка ацетона', 250);
INSERT INTO public.cargo (name, weight) VALUES ('Рулон тента', 40);