INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Ford', 3000, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Toyota', 2700, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Nissan', 2800, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Chevrolet', 3100, 9);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Honda', 2600, 6);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('BMW', 2500, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Mercedes-Benz', 3200, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Volkswagen', 2900, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Kia', 2700, 6);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Hyundai', 2600, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Subaru', 2400, 6);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Mazda', 2500, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Mitsubishi', 2800, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Jeep', 3000, 9);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Dodge', 3100, 9);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Ram', 3500, 10);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('GMC', 3300, 9);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Lexus', 2600, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Infiniti', 2700, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Acura', 2500, 6);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Cadillac', 2900, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Lincoln', 3000, 9);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Chrysler', 2800, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Buick', 2700, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Tesla', 2400, 5);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Volvo', 2600, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Land Rover', 3200, 10);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Jaguar', 2500, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Porsche', 2600, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Ferrari', 2000, 10);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Lamborghini', 2100, 12);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Maserati', 2200, 9);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Alfa Romeo', 2300, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Peugeot', 2400, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Citroën', 2300, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Renault', 2500, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Fiat', 2200, 6);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Opel', 2600, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Vauxhall', 2500, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Seat', 2400, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Skoda', 2500, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Suzuki', 2200, 6);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Isuzu', 3100, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('SsangYong', 2900, 9);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Great Wall', 2800, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Chery', 2700, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Geely', 2600, 6);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('BYD', 2500, 6);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Haval', 2900, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('FAW', 3000, 9);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('JAC', 3100, 9);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Dongfeng', 3200, 9);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Lifan', 2600, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Brilliance', 2500, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('BAIC', 2700, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Roewe', 2600, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('MG', 2500, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Tata', 2800, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Mahindra', 2900, 9);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Proton', 2700, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Perodua', 2600, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Holden', 3000, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('HSV', 3200, 10);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Foton', 3100, 9);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Kamaz', 10000, 35);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('ZIL', 9000, 32);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('GAZ', 8000, 30);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('UAZ', 3500, 12);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Lada', 2200, 6);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('VAZ', 2300, 6);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Moskvich', 2400, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('SAIPA', 2500, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('IKCO', 2700, 8);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Proton', 2600, 7);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Scania', 13000, 40);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('MAN', 12500, 38);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('DAF', 12800, 39);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Iveco', 12000, 36);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Kenworth', 13500, 42);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Peterbilt', 13700, 44);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Mack', 14000, 45);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Volvo Trucks', 13200, 40);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Freightliner', 13800, 43);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Western Star', 13600, 42);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Hino', 11500, 35);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('UD Trucks', 11700, 34);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Fuso', 11000, 33);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Tata Motors', 10500, 32);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Ashok Leyland', 10800, 34);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Mahindra Trucks', 10700, 33);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Dongfeng Trucks', 12000, 36);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Sinotruk', 12500, 38);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('FAW Trucks', 12300, 37);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('JAC Trucks', 11500, 35);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Shacman', 13000, 39);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Kamaz Trucks', 14000, 45);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Maz Trucks', 13500, 43);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('Ural Trucks', 12800, 40);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('GAZ Trucks', 11000, 34);
INSERT INTO public.car_brands (name, load_capacity, fuel_consumption) VALUES ('UAZ Trucks', 9000, 32);